### ISSUE TITLE
Add custom data fields for Android push 

### ISSUE THREAD

**Issue by renefloor** [PharmIT/Push#2]
As discussed in https://github.com/PharmIT/Push/pull/1 
It would be good when the possibility is introduced to add other fields than only message or title. In the Android push platform you can use any field you want.

**Comment by nickygerritsen** [comment]
Apple can also have custom fields.

Probably add a general `setField($field, $value)` function to the interface and implementations?

**Comment by renefloor** [comment]
Didn't know the implementation of Apple, than that makes sense yes.

**Comment by johnroyer** [comment]
In [this document](https://developers.google.com/cloud-messaging/concept-options#components-of-a-message), custom field can be set in array `data` (the same as `title` and `content`). I think it is great to add a method `setField()`, or maybe `setFields(['fieldName' => 'key', ...])`.

APNS notification [payload structure](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW2) in HTTP2 version seems different from GCM. I can not find the old version APNS API document which using socket to send payload. Is this library plan to suppport old version of APNS API ?

**Comment by jszanto** [comment]
This has been resolved in [1.0.4](https://github.com/PharmIT/Push/tree/1.0.4) I believe. There are currently no plans to support older versions of the APNS API.
